name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1) Checkout your code
    - uses: actions/checkout@v3

    # 2) Authenticate to GCP using the service account key
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # 3) Set up the Cloud SDK and configure ADC
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    # 4) Configure Docker authentication for Container Registry
    - name: Configure Docker
      run: |
        gcloud auth configure-docker

    # 5) Build & push the Docker image to Container Registry
    - name: Build & Push Docker image
      run: |
        gcloud builds submit . \
          --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }}

    # 6) Deploy the pushed image to Cloud Run
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v0
      with:
        service: ${{ secrets.SERVICE_NAME }}
        image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }}
        region: ${{ secrets.REGION }}
        allow_unauthenticated: true
        set_env_vars: |
          SOLAPI_API_KEY=${{ secrets.SOLAPI_API_KEY }}
          SOLAPI_API_SECRET=${{ secrets.SOLAPI_API_SECRET }}
          SOLAPI_SENDER=${{ secrets.SOLAPI_SENDER }}
          QUEUE_LOCATION=${{ secrets.QUEUE_LOCATION }}
          QUEUE_ID=${{ secrets.QUEUE_ID }}
